# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f17df791fa2bf3e72b17ba101671dc4b0328d6dc9e23c86e6ef2362a27dc22edda9b2efb855380d3a6bf05f08e9db945cc442e91f64a8f92571f558e53095548

test:
  secret_key_base: 0bdbd2a1652fa3261103cf68e424d331ae5d74e855652960c1eea31cb806ad15e6048e944d30e3da1d4a270b1a3524cb6dc90aef42e3ecaaf53b08406f60740c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
